services:
  - type: web
    name: kb-cloud
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    regions:
      - ohio
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENV
        value: gcp-starter
      - key: PINECONE_INDEX
        value: kb-cloud
      - key: R2_ENDPOINT
        sync: false
      - key: R2_ACCESS_KEY
        sync: false
      - key: R2_SECRET_KEY
        sync: false
      - key: R2_BUCKET_ORIGINALS
        value: kb-originals
      - key: R2_BUCKET_EXTRACTED
        value: kb-extracted
      - key: JINA_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: JINA_EMBED_MODEL
        value: jina-embeddings-v3
      - key: JINA_EMBED_DIM
        value: "1024"
      - key: SUPABASE_ENABLE_AUTH
        value: "true"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
